<a href="https://colab.research.google.com/github/Risha-art/MAT-422/blob/main/HW_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**1.2.1 Linear Spaces**

This example will illustrate how linear combinations are calculated.

A linear combination is an expression constructed from a set of terms multiplying each term with a constant and summing the results.

If vector u is a linear combination of vectors v and w, then u is also in the span of vectors v and w. This is because the span is the set of all linear combinations of the two vectors v and w.



In [5]:
import numpy as np
#Define three vectors in R^3
u1 = np.array([0,0,1])
u2 = np.array([0,1,0])
u3 = np.array([1,0,0])
print("Three vectors u1,u2,and u3 are", u1,u2,u3)
#Define vector y as the vector we want to express as a linear combination of u vectors.
y = ([4.5,3.7,2.9])
print("We want to express vector y as a linear combination of vectors u1,u2,and u3: y=", y)
# To express vector y as a linear combination, we need to solve for the scalars.
scalars = np.linalg.solve(u,y)

#Set constants equal to elements of the scalars.
c1 = scalars[0]
c2 = scalars[1]
c3 = scalars[2]
print("The following are the scalars c1, c2, and c3: ", c1,c2,c3)
lin_comb = c1 * u1 + c2 * u2 + c3 * u3
print("Linear combination of c1 * u1 + c2 * u2 + c3 * u3: ", lin_comb)


Three vectors u1,u2,and u3 are [0 0 1] [0 1 0] [1 0 0]
We want to express vector y as a linear combination of vectors u1.u2.and u3: y= [4.5, 3.7, 2.9]
The following are the scalars c1, c2, and c3:  2.9 3.7 4.5
Linear combination of c1 * u1 + c2 * u2 + c3 * u3:  [4.5 3.7 2.9]


## **1.2.2 Orthogonality**

This following exercise illustrates the Pythagorean theorem.

In [10]:
A = np.random.randint(low=0, high=10, size=(3,3))
B= np.random.randint(low=0, high=10, size=(3,3))

print("Random 3x3 Matrix:\n", A)
print("Random 3x3 Matrix:\n",B)


Random 3x3 Matrix:
 [[3 4 7]
 [7 3 7]
 [3 1 5]]
Random 3x3 Matrix:
 [[1 0 3]
 [1 8 3]
 [6 9 7]]


Given two vectors u and v, vector c is the orthogonal projection of u on v as the tip of the vector projection coincides with the perpendicular line drawn from the tip of u to v.

In [21]:
u = A[0,:]
v = B[0,:]
print("Vector u:", u)
print("Vector v:",v)
proj = v * np.dot(u,v) / np.dot(v,v)
print("Vector Projection of u onto v:", proj)




Vector u: [3 4 7]
Vector v: [1 0 3]
Vector Projection of u onto v: [2.4 0.  7.2]


## **1.2.3 Gram - Schmidt Process** ##


This part of the code will illustrate how we can use the Gram-Schmidt Process to make an orthonormal basis for a vector space given any set of vectors that form a basis. In other words, the Gram-Schmidt process takes a set of linearly independent vectors and generates an orthonormal set of vectors spanning the same subspace.

In [39]:
v1 = np.array([1,-1,1])
v2 = np.array([1, 0, 1])
v3 = np.array([1,1,2])

print("Consider the basis in R^3 of v1,v2,and v3=", v1,v2, v3)

u1 = v1
print("Set u1 as v1:", u1)

u2 = v2 - (np.dot(v2,u1)/ np.dot(u1,u1)) * u1
print("Calculate u2 = ", u2)

u3 = v3 - ((np.dot(v3,u1)/ np.dot(u1,u1)) * u1) - ((np.dot(v3,u2)/ np.dot(u2,u2)) * u2)
print("Calculate u3 = ", u3)

print("These three vectors form an orthogonal basis.But if we want an orthonormal basis, we divide each vector by its length.")

w1 = u1/ np.sqrt(np.dot(u1,u1))
w2 = u2/ np.sqrt(np.dot(u2,u2))
w3 = u3/ np.sqrt(np.dot(u3,u3))

print("These are the three vectors that form an orthonormal basis: \n", w1,w2,w3)



Consider the basis in R^3 of v1,v2,and v3= [ 1 -1  1] [1 0 1] [1 1 2]
Set u1 as v1: [ 1 -1  1]
Calculate u2 =  [0.33333333 0.66666667 0.33333333]
Calculate u3 =  [-0.5  0.   0.5]
These three vectors form an orthogonal basis.But if we want an orthonormal basis, we divide each vector by its length.
These are the three vectors that form an orthonormal basis: 
 [ 0.57735027 -0.57735027  0.57735027] [0.40824829 0.81649658 0.40824829] [-0.70710678  0.          0.70710678]


## **1.2.4 Eigenvalues & Eigenvectors**

Power Method

Here is an iterative method to find the largest Eigenvalue and the corresponding Eigenvector

In [59]:
print("Matrix A of order n has n linearly independent eigen vectors.")
a1 = np.array([1, -3, 2])
a2 = np.array([4,4,-1])
a3 = np.array([6,3,5])
print("Consider matrix A made of three eigen vectors:", a1,a2,a3)

X0 = np.array([1, 1, 1])
print("Take initial value as X0=", X0)
iteration1 = np.array([np.dot(a1,X0), np.dot(a2,X0), np.dot(a3,X0)])
print("For iteration 1, calculate the multiplication of matrix A with eigenvector X0\n", iteration1)
finalX0 = iteration1/14
print("The largest eigen value is 14, so divide the resulting eigenvector by 14 for \n the first iteration's eigenvector equal to 14 * ", finalX0)

iteration2 = np.array([np.dot(a1,finalX0), np.dot(a2,finalX0), np.dot(a3,finalX0)])

print("For iteration 2, calculate the multiplication of matrix A with eigenvector finalX0\n", iteration2)
finalX1 = iteration2/6.5

print("The largest eigen value is 6.5, so divide the resulting eigenvector by 6.5 for \n the second iteration's eigenvector equal to 6.5 * ", finalX1)

iteration3 = np.array([np.dot(a1,finalX1), np.dot(a2,finalX1), np.dot(a3,finalX1)])
print("For iteration 3, calculate the multiplication of matrix A with eigenvector finalX1\n", iteration3)
finalX2 = iteration3/5.92307692
print("The largest eigen value is 5.92307692, so divide the resulting eigenvector by 5.92307692 for \n the second iteration's eigenvector equal to 5.92307692 * ", finalX1)

print("At the end of iteration 3, the largest eigenvalue = 5.92307692 and Eigenvector is ", finalX1)





Matrix A of order n has n linearly independent eigen vectors.
Consider matrix A made of three eigen vectors: [ 1 -3  2] [ 4  4 -1] [6 3 5]
Take initial value as X0= [1 1 1]
For iteration 1, calculate the multiplication of matrix A with eigenvector X0
 [ 0  7 14]
The largest eigen value is 14, so divide the resulting eigenvector by 14 for 
 the first iteration's eigenvector equal to 14 *  [0.  0.5 1. ]
For iteration 2, calculate the multiplication of matrix A with eigenvector finalX0
 [0.5 1.  6.5]
The largest eigen value is 6.5, so divide the resulting eigenvector by 6.5 for 
 the second iteration's eigenvector equal to 6.5 *  [0.07692308 0.15384615 1.        ]
For iteration 3, calculate the multiplication of matrix A with eigenvector finalX1
 [ 1.61538462 -0.07692308  5.92307692]
The largest eigen value is 5.92307692, so divide the resulting eigenvector by 5.92307692 for 
 the second iteration's eigenvector equal to 5.92307692 *  [0.07692308 0.15384615 1.        ]
At the end of iterat